version: '3.8'

services:
   web:
       build: .
       command: python /usr/src/artist_catalog/manage.py runserver 0.0.0.0:8000
       volumes:
         - .:/usr/src/artist_catalog
       ports:
           - 8000:8000